[versions]
kotlin-version = "2.1.10"
ktor-version = "3.1.1"
mcp-kotlin-sdk-version = "0.3.0"
slf4j-nop-version = "2.0.9"

[libraries]
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor-version" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor-version" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor-version" }
modelcontextprotocol-kotlin-sdk = { group = "io.modelcontextprotocol", name = "kotlin-sdk", version.ref = "mcp-kotlin-sdk-version" }
slf4j-nop = { group = "org.slf4j", name = "slf4j-nop", version.ref = "slf4j-nop-version" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor-version" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-version" }